-- P0-0 schema baseline
-- Captured at: 2026-06-11
-- Environment: production-equivalent JDBC from bms/disconf/download/DS_ds0_conf.properties
-- Database: tmall_bms
-- Query mode: read-only SHOW CREATE TABLE

CREATE TABLE `fee_detail` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `fee_no` varchar(64) NOT NULL COMMENT '费用编号',
  `bill_id` bigint(20) unsigned NOT NULL COMMENT '账单ID',
  `bill_no` varchar(64) NOT NULL COMMENT '账单编号',
  `bill_config_id` bigint(20) unsigned NOT NULL COMMENT '账单配置ID',
  `business_type_code` varchar(64) DEFAULT NULL COMMENT '命中的业务类型编码',
  `business_type_fee_id` bigint(20) unsigned DEFAULT NULL COMMENT '命中的业务类型费项关联ID',
  `generate_task_id` bigint(20) unsigned DEFAULT NULL COMMENT '生成任务ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员/客户编码',
  `fee_index_id` bigint(20) unsigned NOT NULL COMMENT '费项索引ID',
  `fee_source_rule_id` bigint(20) unsigned DEFAULT NULL COMMENT '费项数据来源规则ID',
  `fee_code` varchar(64) NOT NULL COMMENT '费项编码',
  `fee_name` varchar(128) NOT NULL COMMENT '费项名称',
  `fee_type` varchar(16) NOT NULL COMMENT '费用类型：AR/ARD/AP/ARAP',
  `attached_object` varchar(16) NOT NULL COMMENT '挂靠对象：BILL/ORDER/LAST_PACKAGE/FIRST_PACKAGE',
  `business_order_no` varchar(64) DEFAULT NULL COMMENT '业务主单号',
  `destination_country` varchar(64) DEFAULT NULL COMMENT '集运目的国',
  `consolidation_warehouse_code` varchar(64) DEFAULT NULL COMMENT '集运仓编码',
  `last_mile_waybill_no` varchar(64) DEFAULT NULL COMMENT '尾程运单号',
  `first_mile_waybill_no` varchar(64) DEFAULT NULL COMMENT '首程运单号',
  `source_system` varchar(64) NOT NULL COMMENT '来源系统',
  `source_table` varchar(128) NOT NULL COMMENT '来源表',
  `source_id` varchar(128) NOT NULL COMMENT '来源数据ID',
  `source_order_id` varchar(128) DEFAULT NULL COMMENT '来源业务主单ID',
  `source_bill_no` varchar(128) DEFAULT NULL COMMENT '来源财务账单号',
  `source_biz_no` varchar(128) DEFAULT NULL COMMENT '来源业务单号',
  `source_fee_field` varchar(128) DEFAULT NULL COMMENT '来源金额字段',
  `source_fee_time` datetime DEFAULT NULL COMMENT '来源费用发生时间',
  `source_pay_status` varchar(64) DEFAULT NULL COMMENT '来源费用支付状态',
  `source_row_hash` varchar(64) DEFAULT NULL COMMENT '来源关键字段哈希，用于检测来源数据变化',
  `source_extra_json` json DEFAULT NULL COMMENT '来源扩展快照JSON',
  `dedupe_key` varchar(255) NOT NULL COMMENT '费用幂等键',
  `fee_currency` varchar(16) NOT NULL COMMENT '费用原始币种',
  `amount_fee_currency` decimal(18,4) NOT NULL COMMENT '费用金额<原始币种>',
  `exchange_rate_to_bill` decimal(18,8) DEFAULT NULL COMMENT '原始币种到账单币种汇率',
  `exchange_rate_level_to_bill` varchar(16) DEFAULT NULL COMMENT '汇率级别',
  `bill_currency` varchar(16) NOT NULL COMMENT '账单币种',
  `amount_bill_currency` decimal(18,4) NOT NULL COMMENT '费用金额<账单币种>',
  `exchange_rate_to_fin` decimal(18,8) DEFAULT NULL COMMENT '账单币种到本位币汇率',
  `exchange_rate_level_to_fin` varchar(16) DEFAULT NULL COMMENT '汇率级别',
  `fin_currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '财务本位币',
  `amount_fin_currency` decimal(18,4) NOT NULL COMMENT '费用金额<本位币>',
  `fee_status` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '费用状态：NORMAL/ADJUSTED/REVERSED/VOID',
  `manual_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否手工补录：0否，1是',
  `manual_reason` varchar(500) DEFAULT NULL COMMENT '手工补录原因',
  `original_fee_id` bigint(20) unsigned DEFAULT NULL COMMENT '原费用ID，红冲/调账时使用',
  `offset_bill_no` varchar(64) DEFAULT NULL COMMENT '对冲账单号',
  `voucher_url` varchar(500) DEFAULT NULL COMMENT '费用凭证URL',
  `voucher_supplier` varchar(128) DEFAULT NULL COMMENT '费用凭证供应商',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fee_no` (`fee_no`),
  UNIQUE KEY `uk_fee_dedupe` (`dedupe_key`),
  KEY `idx_fee_bill` (`bill_id`,`fee_type`,`fee_status`),
  KEY `idx_fee_config` (`bill_config_id`,`fee_code`),
  KEY `idx_fee_business_type` (`business_type_code`,`business_type_fee_id`),
  KEY `idx_fee_country_wh` (`destination_country`,`consolidation_warehouse_code`),
  KEY `idx_fee_subject_time` (`sc_id`,`shop_id`,`user_id`,`member_code`,`source_fee_time`),
  KEY `idx_fee_order` (`business_order_no`),
  KEY `idx_fee_last_waybill` (`last_mile_waybill_no`),
  KEY `idx_fee_first_waybill` (`first_mile_waybill_no`),
  KEY `idx_fee_source` (`source_system`,`source_table`,`source_id`),
  KEY `idx_fee_source_rule` (`fee_source_rule_id`),
  KEY `idx_fee_original` (`original_fee_id`)
) ENGINE=InnoDB AUTO_INCREMENT=614 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='费用详情/费用快照';

CREATE TABLE `bill_config` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `config_no` varchar(64) NOT NULL COMMENT '账号/账单配置编号',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员/客户编码',
  `member_name` varchar(128) DEFAULT NULL COMMENT '会员/客户名称',
  `customer_no` varchar(64) DEFAULT NULL COMMENT '外部客户编号',
  `bill_name` varchar(128) NOT NULL COMMENT '账单配置名称',
  `bill_type` varchar(32) NOT NULL DEFAULT 'MEMBER_AR' COMMENT '账单类型：MEMBER_AR客户应收等',
  `business_type_codes` varchar(500) NOT NULL COMMENT '适用业务类型编码，多选逗号分隔，如PEER,ECOMMERCE,CONSOLIDATION',
  `config_type` varchar(16) NOT NULL DEFAULT 'DEFAULT' COMMENT '配置类型：DEFAULT默认配置，BRANCH分支配置',
  `parent_config_id` bigint(20) unsigned DEFAULT NULL COMMENT '父配置ID，分支配置指向默认配置',
  `priority` int(11) NOT NULL DEFAULT '0' COMMENT '匹配优先级，数值越小越优先；默认配置建议9999',
  `billing_currency` varchar(16) NOT NULL COMMENT '账单结算币种',
  `billing_period_type` varchar(32) NOT NULL COMMENT '账期类型：DAY/WEEK/HALF_MONTH/MONTH',
  `fin_currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '财务本位币',
  `bill_send_offset_days` int(11) NOT NULL DEFAULT '0' COMMENT '账单结束后第几天发送账单',
  `contract_node` varchar(64) DEFAULT NULL COMMENT '履约/归集节点',
  `credit_period_days` int(11) NOT NULL DEFAULT '0' COMMENT '信用期天数',
  `credit_level` varchar(32) DEFAULT NULL COMMENT '信用评级',
  `advance_limit_amount` decimal(18,4) DEFAULT NULL COMMENT '垫付/预支额度',
  `overdue_penalty_rate` decimal(10,6) DEFAULT NULL COMMENT '逾期费率',
  `effective_start_date` date NOT NULL COMMENT '生效开始日期',
  `effective_end_date` date DEFAULT NULL COMMENT '生效结束日期',
  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态：1启用，0停用',
  `version` int(11) NOT NULL DEFAULT '1' COMMENT '版本号',
  `is_current_version` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否当前版本',
  `extra_json` json DEFAULT NULL COMMENT '扩展配置JSON',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0否，1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bill_config_version` (`config_no`,`version`),
  KEY `idx_bill_config_customer` (`sc_id`,`shop_id`,`user_id`,`member_code`,`status`,`is_deleted`),
  KEY `idx_bill_config_current` (`sc_id`,`shop_id`,`user_id`,`member_code`,`config_type`,`is_current_version`,`is_deleted`),
  KEY `idx_bill_config_parent` (`parent_config_id`,`config_type`,`priority`,`status`,`is_deleted`),
  KEY `idx_bill_config_effective` (`effective_start_date`,`effective_end_date`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='账号/账单配置：默认配置/目的国仓库分支配置';

CREATE TABLE `bill_generate_task` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `task_no` varchar(64) NOT NULL COMMENT '任务编号',
  `bill_config_id` bigint(20) unsigned NOT NULL COMMENT '账单配置ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员/客户编码',
  `billing_period_start_date` date NOT NULL COMMENT '账期开始日期',
  `billing_period_end_date` date NOT NULL COMMENT '账期结束日期',
  `task_status` varchar(32) NOT NULL COMMENT '任务状态：INIT/RUNNING/SUCCESS/FAILED/CANCELED',
  `trigger_type` varchar(32) NOT NULL DEFAULT 'SCHEDULE' COMMENT '触发方式：SCHEDULE/MANUAL/RETRY',
  `idempotent_key` varchar(128) NOT NULL COMMENT '任务幂等键',
  `retry_count` int(11) NOT NULL DEFAULT '0' COMMENT '重试次数',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `duration_ms` bigint(20) DEFAULT '0' COMMENT '执行耗时毫秒',
  `pulled_order_count` int(11) NOT NULL DEFAULT '0' COMMENT '拉取订单数',
  `matched_order_count` int(11) NOT NULL DEFAULT '0' COMMENT '命中出账订单数',
  `skipped_order_count` int(11) NOT NULL DEFAULT '0' COMMENT '跳过订单数',
  `fee_detail_count` int(11) NOT NULL DEFAULT '0' COMMENT '生成费用明细数',
  `additional_fee_count` int(11) NOT NULL DEFAULT '0' COMMENT '生成附加费明细数',
  `failed_count` int(11) NOT NULL DEFAULT '0' COMMENT '失败数据数',
  `receivable_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '本任务生成应收金额',
  `error_message` varchar(2000) DEFAULT NULL COMMENT '错误信息',
  `bill_config_snapshot_json` json DEFAULT NULL COMMENT '账单配置快照JSON',
  `bill_scope_snapshot_json` json DEFAULT NULL COMMENT '账单配置范围快照JSON',
  `fee_rule_snapshot_json` json DEFAULT NULL COMMENT '费项规则快照JSON',
  `order_source_sql` longtext COMMENT '本次任务拉取主订单宽表实际执行SQL',
  `additional_source_sql` longtext COMMENT '本次任务拉取附加费实际执行SQL',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_idempotent` (`idempotent_key`),
  UNIQUE KEY `uk_task_period` (`bill_config_id`,`billing_period_start_date`,`billing_period_end_date`,`trigger_type`),
  KEY `idx_task_status` (`task_status`,`created_at`),
  KEY `idx_task_subject_period` (`sc_id`,`shop_id`,`user_id`,`member_code`,`billing_period_start_date`)
) ENGINE=InnoDB AUTO_INCREMENT=98 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='账单生成任务';

CREATE TABLE `bill_exchange_rate` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `bill_id` bigint(20) unsigned NOT NULL COMMENT '账单ID',
  `bill_no` varchar(64) NOT NULL COMMENT '账单编号',
  `bill_currency` varchar(16) NOT NULL COMMENT '目标币种',
  `conversion_currency` varchar(16) NOT NULL COMMENT '来源币种',
  `conversion_currency_type` varchar(32) NOT NULL COMMENT '转换类型：FEE_TO_BILL费项原始币种转账单结算币种，BILL_TO_FIN账单结算币种转财务本位币',
  `conversion_direction` varchar(8) NOT NULL COMMENT '换算方向：MUL/DIV',
  `exchange_rate` decimal(18,8) NOT NULL COMMENT '锁定汇率',
  `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用：1启用，0关闭',
  `rate_date` date DEFAULT NULL COMMENT '汇率日期',
  `rate_source` varchar(64) DEFAULT NULL COMMENT '汇率来源',
  `source_type` varchar(16) NOT NULL DEFAULT 'SYSTEM' COMMENT '来源：SYSTEM系统，MANUAL人工',
  `edit_reason` varchar(500) DEFAULT NULL COMMENT '人工编辑原因',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bill_rate` (`bill_id`,`bill_currency`,`conversion_currency`,`conversion_currency_type`),
  KEY `idx_bill_rate_no` (`bill_no`)
) ENGINE=InnoDB AUTO_INCREMENT=64 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='账单汇率';

CREATE TABLE `ar_bill` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `bill_no` varchar(64) NOT NULL COMMENT '账单编号',
  `bill_title` varchar(128) NOT NULL COMMENT '账单标题',
  `bill_status` varchar(32) NOT NULL COMMENT '账单状态：DRAFT/GENERATED/CONFIRMED/PART_PAID/PAID/VOID',
  `bill_config_id` bigint(20) unsigned NOT NULL COMMENT '账单配置ID',
  `config_type` varchar(16) NOT NULL COMMENT '配置类型：DEFAULT默认配置，BRANCH分支配置',
  `generate_task_id` bigint(20) unsigned DEFAULT NULL COMMENT '生成任务ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员/客户编码',
  `member_name` varchar(128) DEFAULT NULL COMMENT '会员/客户名称',
  `customer_no` varchar(64) DEFAULT NULL COMMENT '外部客户编号',
  `customer_name` varchar(128) DEFAULT NULL COMMENT '外部客户名称',
  `destination_country` varchar(64) DEFAULT NULL COMMENT '集运目的国',
  `business_sector` varchar(64) DEFAULT NULL COMMENT '业务板块',
  `consolidation_warehouse_code` varchar(64) DEFAULT NULL COMMENT '集运仓编码',
  `billing_cycle_type` varchar(32) NOT NULL COMMENT '账期类型',
  `billing_period_start_date` date NOT NULL COMMENT '账期开始日期',
  `billing_period_end_date` date NOT NULL COMMENT '账期结束日期',
  `bill_send_date` date DEFAULT NULL COMMENT '账单发送日',
  `credit_period_end_date` date DEFAULT NULL COMMENT '信用期结束日',
  `payment_overdue_days` int(11) NOT NULL DEFAULT '0' COMMENT '付款逾期天数',
  `bill_currency` varchar(16) NOT NULL COMMENT '账单结算币种',
  `fin_currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '财务本位币',
  `initial_receivable_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '初始应收金额<账单币种>',
  `this_adjustment_delta_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '本期调整增量<账单币种>',
  `previous_adjustment_delta_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '往期调整增量<账单币种>',
  `late_fee_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '滞纳金<账单币种>',
  `receivable_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '应收金额<账单币种>',
  `paid_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '已核销金额<账单币种>',
  `unpaid_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '未核销金额<账单币种>',
  `receivable_amount_fin` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '应收金额<本位币>',
  `paid_amount_fin` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '已核销金额<本位币>',
  `confirmed_at` datetime DEFAULT NULL COMMENT '确认时间',
  `confirmed_by` varchar(64) DEFAULT NULL COMMENT '确认人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0否，1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ar_bill_no` (`bill_no`),
  UNIQUE KEY `uk_ar_bill_period_sector_country` (`bill_config_id`,`billing_period_start_date`,`billing_period_end_date`,`business_sector`,`destination_country`),
  KEY `idx_ar_bill_customer_status` (`sc_id`,`shop_id`,`user_id`,`member_code`,`bill_status`,`is_deleted`),
  KEY `idx_ar_bill_config_type` (`bill_config_id`,`config_type`),
  KEY `idx_ar_bill_country_wh` (`destination_country`,`consolidation_warehouse_code`),
  KEY `idx_ar_bill_period` (`billing_period_start_date`,`billing_period_end_date`),
  KEY `idx_ar_bill_customer_no` (`customer_no`),
  KEY `idx_ar_bill_task` (`generate_task_id`),
  KEY `idx_ar_bill_sector_country` (`business_sector`,`destination_country`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='应收账单';

CREATE TABLE `ar_bill_currency_summary` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `bill_id` bigint(20) unsigned NOT NULL COMMENT '账单ID',
  `bill_no` varchar(64) NOT NULL COMMENT '账单编号',
  `currency` varchar(16) NOT NULL COMMENT '收费币种',
  `fin_currency` varchar(16) DEFAULT NULL COMMENT '财务本位币',
  `receivable_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '应收金额',
  `paid_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '已核销金额',
  `unpaid_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '未核销金额',
  `fee_count` int(11) NOT NULL DEFAULT '0' COMMENT '费用明细数',
  `order_count` int(11) NOT NULL DEFAULT '0' COMMENT '涉及订单数',
  `summary_status` varchar(32) NOT NULL DEFAULT 'WAITING_PAY' COMMENT '币种核销状态：WAITING_PAY待收款，PART_PAID部分核销，PAID已核销',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bill_currency_summary` (`bill_no`,`currency`),
  KEY `idx_currency_summary_bill` (`bill_id`),
  KEY `idx_currency_summary_status` (`currency`,`summary_status`)
) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=utf8mb4 COMMENT='应收账单按币种汇总';

CREATE TABLE `refund_bill_config` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `config_no` varchar(64) NOT NULL COMMENT '返款配置编号，格式：RCB-{customerNo}-{timestamp}',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `customer_info_id` bigint(20) DEFAULT NULL COMMENT '客户信息ID（关联 store-service 客户快照）',
  `member_code` varchar(64) NOT NULL COMMENT '会员编码',
  `member_name` varchar(128) DEFAULT NULL COMMENT '客户名称快照',
  `customer_no` varchar(64) DEFAULT NULL COMMENT '客户编码',
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态：1启用，0停用',
  `refund_mode` varchar(32) NOT NULL COMMENT '返款模式：SIGNED 签收返款 / RECEIVED 回款返款',
  `billing_period_type` varchar(32) NOT NULL COMMENT '账期类型：WEEK/HALF_MONTH/MONTH/TEN_DAYS/FIFTEEN_DAYS',
  `billing_period_start_days` varchar(32) DEFAULT NULL COMMENT '账期起始日，半周账期保存两个星期值，逗号分隔（1周一，7周日）',
  `bill_send_offset_days` int(11) NOT NULL DEFAULT '2' COMMENT '账期结束后第几天预定发出账单',
  `cod_service_fee_rate` decimal(10,6) NOT NULL DEFAULT '0.030000' COMMENT '代收货款手续费比例，0.03 表示 3%',
  `config_snapshot_json` json DEFAULT NULL COMMENT '一期页面配置快照 JSON：含币种账户矩阵与直接扣减费项',
  `effective_start_date` date NOT NULL COMMENT '生效开始日期',
  `effective_end_date` date DEFAULT NULL COMMENT '生效结束日期',
  `version` int(11) NOT NULL DEFAULT '1' COMMENT '版本号',
  `is_current_version` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否当前版本：1是，0否',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0否，1是',
  `current_version_guard` tinyint(1) GENERATED ALWAYS AS ((case when ((`is_current_version` = 1) and (`is_deleted` = 0)) then 1 else NULL end)) STORED COMMENT '当前版本唯一约束辅助列（is_current_version=1 且未删除时为1，否则NULL）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_config_version` (`config_no`,`version`),
  UNIQUE KEY `uk_refund_config_current` (`sc_id`,`shop_id`,`user_id`,`member_code`,`current_version_guard`),
  KEY `idx_refund_config_customer` (`sc_id`,`shop_id`,`user_id`,`member_code`,`status`,`is_deleted`),
  KEY `idx_refund_config_effective` (`effective_start_date`,`effective_end_date`,`status`,`is_deleted`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COMMENT='COD 返款账单配置（一期）';

-- bill_fee_detail_relation
-- SHOW CREATE TABLE failed with:
--   ER_NO_SUCH_TABLE: Table 'tmall_bms.bill_fee_detail_relation' doesn't exist
