-- ============================================================
-- BMS COD 返款账单基础能力 DDL（P1）
-- ============================================================
-- 说明：
-- 1. 本脚本只建立返款账单主表、币种汇总和向客户返款打款流水。
-- 2. 返款费用事实后续统一写入 bill_fee_detail_relation，本脚本不复制返款费用明细表。
-- 3. 执行前必须在生产等价环境演练，并确认表不存在。
-- ============================================================

CREATE TABLE `refund_bill` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `bill_no` varchar(64) NOT NULL COMMENT '返款账单编号',
  `bill_type` varchar(32) NOT NULL DEFAULT 'COD_REFUND' COMMENT '账单类型：COD_REFUND',
  `bill_status` varchar(32) NOT NULL COMMENT '状态：DRAFT/UNDER_REVIEW/PENDING_SETTLEMENT/SETTLED/VOID',
  `refund_bill_config_id` bigint(20) unsigned NOT NULL COMMENT '返款配置历史版本ID',
  `refund_bill_config_no` varchar(64) NOT NULL COMMENT '返款配置编号快照',
  `refund_bill_config_version` int(11) NOT NULL COMMENT '返款配置版本快照',
  `config_snapshot_json` json DEFAULT NULL COMMENT '返款配置完整快照',
  `generate_task_id` bigint(20) unsigned DEFAULT NULL COMMENT '生成任务ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `customer_info_id` bigint(20) DEFAULT NULL COMMENT '客户信息ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员编码',
  `member_name` varchar(128) DEFAULT NULL COMMENT '客户名称快照',
  `customer_no` varchar(64) DEFAULT NULL COMMENT '客户编码',
  `refund_mode` varchar(32) NOT NULL COMMENT '返款模式：SIGNED/RECEIVED',
  `billing_cycle_type` varchar(32) NOT NULL COMMENT '账期类型：WEEK/HALF_WEEK',
  `billing_period_start_date` date NOT NULL COMMENT '账期开始日期',
  `billing_period_end_date` date NOT NULL COMMENT '账期结束日期',
  `planned_send_date` date DEFAULT NULL COMMENT '计划发出日期',
  `sent_at` datetime DEFAULT NULL COMMENT '实际发送时间',
  `settled_at` datetime DEFAULT NULL COMMENT '结清时间',
  `send_failed_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '发送失败标记：0否，1是',
  `overdue_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逾期未返标记：0否，1是',
  `overdue_days` int(11) NOT NULL DEFAULT '0' COMMENT '逾期天数',
  `fin_currency` varchar(16) NOT NULL COMMENT '财务本位币',
  `principal_amount_fin` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '返款本金本位币汇总',
  `deduction_amount_fin` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '扣减项本位币汇总',
  `refundable_amount_fin` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '应返本位币汇总',
  `refunded_amount_fin` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '已返本位币汇总',
  `unrefunded_amount_fin` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '未返本位币汇总',
  `uncollected_amount_fin` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '未回款风险本位币汇总',
  `reviewed_at` datetime DEFAULT NULL COMMENT '复核时间',
  `reviewed_by` varchar(64) DEFAULT NULL COMMENT '复核人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0否，1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_bill_no` (`bill_no`),
  UNIQUE KEY `uk_refund_bill_period` (`refund_bill_config_id`,`billing_period_start_date`,`billing_period_end_date`),
  KEY `idx_refund_bill_customer_status` (`sc_id`,`shop_id`,`user_id`,`member_code`,`bill_status`,`is_deleted`),
  KEY `idx_refund_bill_period` (`billing_period_start_date`,`billing_period_end_date`),
  KEY `idx_refund_bill_task` (`generate_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='COD返款账单';

CREATE TABLE `refund_bill_currency_summary` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `bill_id` bigint(20) unsigned NOT NULL COMMENT '返款账单ID',
  `bill_no` varchar(64) NOT NULL COMMENT '返款账单编号',
  `currency` varchar(16) NOT NULL COMMENT '货款结算币种',
  `fin_currency` varchar(16) NOT NULL COMMENT '财务本位币',
  `principal_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '返款本金',
  `deduction_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '返款扣减金额',
  `adjustment_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '调整净额',
  `refundable_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '应返金额',
  `refunded_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '已返金额',
  `unrefunded_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '未返金额',
  `pending_deduction_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '待补扣金额',
  `refundable_amount_fin` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '应返本位币金额',
  `refunded_amount_fin` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '已返本位币金额',
  `unrefunded_amount_fin` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '未返本位币金额',
  `summary_status` varchar(32) NOT NULL DEFAULT 'WAITING_REFUND' COMMENT '状态：WAITING_REFUND/PART_REFUNDED/REFUNDED',
  `fee_count` int(11) NOT NULL DEFAULT '0' COMMENT '费用明细数',
  `order_count` int(11) NOT NULL DEFAULT '0' COMMENT '订单数',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_bill_currency` (`bill_no`,`currency`),
  KEY `idx_refund_summary_bill` (`bill_id`),
  KEY `idx_refund_summary_status` (`currency`,`summary_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='COD返款账单币种汇总';

CREATE TABLE `refund_payment_record` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `payment_no` varchar(64) NOT NULL COMMENT '返款打款流水号',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '收款客户会员编码',
  `payment_currency` varchar(16) NOT NULL COMMENT '打款币种',
  `payment_amount` decimal(18,4) NOT NULL COMMENT '打款金额',
  `allocated_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '已分配金额',
  `unallocated_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '未分配金额',
  `payment_channel` varchar(32) DEFAULT NULL COMMENT '打款渠道',
  `paid_at` datetime NOT NULL COMMENT '实际打款时间',
  `payment_status` varchar(32) NOT NULL COMMENT '打款状态：ALLOCATED/REVERSED/VOID',
  `voucher_url` varchar(500) DEFAULT NULL COMMENT '打款凭证',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0否，1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_payment_no` (`payment_no`),
  KEY `idx_refund_payment_subject` (`sc_id`,`shop_id`,`user_id`,`member_code`,`paid_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='向客户返款打款流水';

CREATE TABLE `refund_payment_allocation` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `allocation_no` varchar(64) NOT NULL COMMENT '返款打款分配流水号',
  `payment_id` bigint(20) unsigned NOT NULL COMMENT '返款打款流水ID',
  `payment_no` varchar(64) NOT NULL COMMENT '返款打款流水号',
  `bill_id` bigint(20) unsigned NOT NULL COMMENT '返款账单ID',
  `bill_no` varchar(64) NOT NULL COMMENT '返款账单编号',
  `currency_summary_id` bigint(20) unsigned NOT NULL COMMENT '返款账单币种汇总ID',
  `payment_currency` varchar(16) NOT NULL COMMENT '打款币种',
  `allocation_amount_payment_currency` decimal(18,4) NOT NULL COMMENT '打款币种分配金额',
  `bill_currency` varchar(16) NOT NULL COMMENT '账单结算币种',
  `exchange_rate_to_bill` decimal(18,8) NOT NULL DEFAULT '1.00000000' COMMENT '打款币种到结算币种汇率',
  `allocation_amount_bill_currency` decimal(18,4) NOT NULL COMMENT '结算币种分配金额',
  `fin_currency` varchar(16) NOT NULL COMMENT '财务本位币',
  `exchange_rate_to_fin` decimal(18,8) NOT NULL DEFAULT '1.00000000' COMMENT '结算币种到本位币汇率',
  `allocation_amount_fin_currency` decimal(18,4) NOT NULL COMMENT '本位币分配金额',
  `allocation_status` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '状态：NORMAL/REVERSED/VOID',
  `allocated_at` datetime NOT NULL COMMENT '分配时间',
  `allocated_by` varchar(64) DEFAULT NULL COMMENT '分配人',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_allocation_no` (`allocation_no`),
  KEY `idx_refund_allocation_payment` (`payment_id`),
  KEY `idx_refund_allocation_bill` (`bill_id`,`currency_summary_id`,`allocation_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='返款打款到账单分配';
