stages:
  - deploy

pages:
  stage: deploy
  tags:
    - pages
  image: 192.168.0.242:5000/docs/ai-docs-vitepress-builder:latest
  cache:
    key: "$CI_PROJECT_PATH_SLUG-pages-render-cache"
    paths:
      - .aidocs-cache/
  script:
    - node scripts/build-pages.mjs
  artifacts:
    paths:
      - public/
  only:
    - master
