FROM docker.m.daocloud.io/library/node:20-alpine

WORKDIR /opt/vitepress-builder

RUN npm config set registry https://registry.npmmirror.com \
    && npm install vitepress@1.6.4 vue@3.5.13

RUN apk add --no-cache \
    openjdk17-jre \
    graphviz \
    plantuml \
    fontconfig \
    ttf-dejavu \
    font-noto-cjk

ENV PLANTUML_BIN=plantuml
ENV PLANTUML_LIMIT_SIZE=8192

WORKDIR /work
