/*
 * tmall_bms 集运客户账单初始化表结构
 * MySQL 5.7
 *
 * 设计目标：
 * 1. 支持多供应链、多店铺、多会员：sc_id -> shop_id -> user_id -> member_code。
 * 2. 支持客户默认账单配置，以及按目的国/集运仓匹配的分支账单配置。
 * 3. 支持客户账单配置、费项配置、读取其它业务单据生成费用快照。
 * 4. 支持定时任务生成账单、账单确认、红冲调账、多账单收款核销。
 * 5. 金额统一使用 DECIMAL(18,4)，汇率使用 DECIMAL(18,8)。
 *
 * 注意：
 * - 这是空库初始化 DDL，不包含 DROP TABLE。
 * - 如果要在已有 tmall_bms 上执行，请先基于当前库生成 ALTER 迁移脚本。
 */

CREATE DATABASE IF NOT EXISTS `tmall_bms`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;

USE `tmall_bms`;

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `fee_index` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `fee_code` varchar(64) NOT NULL COMMENT '费项编码',
  `fee_name` varchar(128) NOT NULL COMMENT '费项名称',
  `fee_type` varchar(16) NOT NULL COMMENT '费用类型：AR应收，ARD应收扣减，AP成本，ARAP代收代付',
  `attachment_object` varchar(16) NOT NULL COMMENT '挂靠对象：BILL账单，ORDER业务主单，LAST_PACKAGE尾程包裹，FIRST_PACKAGE首程包裹',
  `legacy_data_source` varchar(255) DEFAULT NULL COMMENT '旧数据源描述，兼容历史数据；新逻辑使用fee_source_rule',
  `scenario_tag` varchar(64) DEFAULT NULL COMMENT '场景标签',
  `applicable_order_source` varchar(255) DEFAULT NULL COMMENT '适用订单来源，逗号分隔',
  `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fee_code` (`fee_code`),
  KEY `idx_fee_type_object` (`fee_type`,`attachment_object`,`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='费项索引';

CREATE TABLE `fee_source_datasource` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `datasource_code` varchar(64) NOT NULL COMMENT '数据源编码，如OFP_DB',
  `datasource_name` varchar(128) NOT NULL COMMENT '数据源名称',
  `source_system` varchar(64) NOT NULL COMMENT '来源系统，如OFP',
  `env_code` varchar(32) NOT NULL DEFAULT 'PROD' COMMENT '环境编码：DEV/TEST/UAT/PROD',
  `db_type` varchar(32) NOT NULL DEFAULT 'MYSQL' COMMENT '数据库类型：MYSQL/POSTGRES/ORACLE等',
  `driver_class_name` varchar(128) DEFAULT NULL COMMENT 'JDBC驱动类名，可为空走默认驱动',
  `jdbc_url` varchar(500) NOT NULL COMMENT 'JDBC连接URL',
  `username` varchar(128) NOT NULL COMMENT '账号',
  `password_cipher` varchar(500) NOT NULL COMMENT '加密后的密码',
  `password_mask` varchar(64) DEFAULT NULL COMMENT '脱敏密码展示，如******',
  `default_database` varchar(64) DEFAULT NULL COMMENT '默认库名',
  `default_schema` varchar(64) DEFAULT NULL COMMENT '默认schema，MySQL可与default_database一致',
  `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `max_pool_size` int(11) NOT NULL DEFAULT '5' COMMENT '最大连接数',
  `connect_timeout_seconds` int(11) NOT NULL DEFAULT '10' COMMENT '连接超时时间',
  `query_timeout_seconds` int(11) NOT NULL DEFAULT '30' COMMENT '查询超时时间',
  `max_rows_per_query` int(11) NOT NULL DEFAULT '50000' COMMENT '单次最大拉取行数',
  `last_test_status` varchar(32) DEFAULT NULL COMMENT '最近一次连接测试状态：SUCCESS/FAILED',
  `last_test_at` datetime DEFAULT NULL COMMENT '最近一次连接测试时间',
  `last_test_message` varchar(500) DEFAULT NULL COMMENT '最近一次连接测试结果',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0否，1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_datasource_code` (`datasource_code`),
  KEY `idx_datasource_system` (`source_system`,`enabled`,`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='费项来源数据源配置';

CREATE TABLE `fee_source_rule` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `fee_index_id` bigint(20) unsigned NOT NULL COMMENT '费项索引ID',
  `fee_code` varchar(64) NOT NULL COMMENT '费项编码快照',
  `source_system` varchar(64) NOT NULL COMMENT '来源系统，如OFP',
  `datasource_code` varchar(64) NOT NULL DEFAULT 'OFP_DB' COMMENT '数据源编码，关联fee_source_datasource.datasource_code',
  `source_database` varchar(64) DEFAULT NULL COMMENT '来源库',
  `source_table` varchar(128) NOT NULL COMMENT '来源表',
  `source_alias` varchar(64) DEFAULT NULL COMMENT '来源别名',
  `source_id_column` varchar(128) NOT NULL COMMENT '来源主键字段，如id',
  `source_biz_no_column` varchar(128) DEFAULT NULL COMMENT '来源业务单号字段',
  `source_amount_column` varchar(128) NOT NULL COMMENT '来源金额字段，如fee_amount',
  `source_currency_column` varchar(128) DEFAULT NULL COMMENT '来源币种字段，如fee_amount_currency',
  `source_converted_amount_column` varchar(128) DEFAULT NULL COMMENT '来源转换后金额字段，如convert_fee_amount',
  `source_converted_currency_column` varchar(128) DEFAULT NULL COMMENT '来源转换后币种字段，如convert_fee_amount_currency',
  `source_time_column` varchar(128) DEFAULT NULL COMMENT '来源费用发生时间字段，如create_time/handle_time',
  `source_ref_columns_json` json COMMENT '来源关联字段映射JSON，如{"billNo":"financial_bill_no","orderId":"sale_order_id","lastWaybillNo":"sub_bill_waybill_no"}',
  `source_tenant_columns_json` json COMMENT '来源租户字段映射JSON，如{"shopId":"shop_id","country":"country_short_code"}',
  `source_status_columns_json` json COMMENT '来源状态字段映射JSON，如{"payStatus":"fee_pay_status","payer":"payer","payMethod":"payment_method"}',
  `source_extra_columns_json` json COMMENT '来源扩展字段映射JSON，如{"fileUrl":"file_url","detailJson":"fee_detail_json"}',
  `filter_expr` varchar(1000) DEFAULT NULL COMMENT '过滤表达式，如 fee_item_type = #{feeItemType} AND fee_amount <> 0',
  `filter_params_json` json COMMENT '过滤参数JSON，如{"feeItemType":"超重费"}',
  `dedupe_key_expr` varchar(500) DEFAULT NULL COMMENT '幂等键表达式',
  `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `priority` int(11) NOT NULL DEFAULT '0' COMMENT '优先级',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fee_source` (`fee_index_id`,`source_system`,`source_database`,`source_table`,`source_amount_column`),
  KEY `idx_datasource_code` (`datasource_code`,`enabled`),
  KEY `idx_source_table` (`source_system`,`source_database`,`source_table`,`enabled`),
  KEY `idx_source_fee_code` (`fee_code`,`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='费项数据来源规则';

CREATE TABLE `bill_config` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `config_no` varchar(64) NOT NULL COMMENT '账号/账单配置编号',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员/客户编码',
  `member_name` varchar(128) DEFAULT NULL COMMENT '会员/客户名称',
  `customer_no` varchar(64) DEFAULT NULL COMMENT '外部客户编号',
  `bill_name` varchar(128) NOT NULL COMMENT '账单配置名称',
  `bill_type` varchar(32) NOT NULL DEFAULT 'MEMBER_AR' COMMENT '账单类型：MEMBER_AR客户应收等',
  `business_type_codes` varchar(500) NOT NULL COMMENT '适用业务类型编码，多选逗号分隔，如PEER,ECOMMERCE,CONSOLIDATION',
  `config_type` varchar(16) NOT NULL DEFAULT 'DEFAULT' COMMENT '配置类型：DEFAULT默认配置，BRANCH分支配置',
  `parent_config_id` bigint(20) unsigned DEFAULT NULL COMMENT '父配置ID，分支配置指向默认配置',
  `priority` int(11) NOT NULL DEFAULT '0' COMMENT '匹配优先级，数值越小越优先；默认配置建议9999',
  `billing_currency` varchar(16) NOT NULL COMMENT '账单结算币种',
  `billing_period_type` varchar(32) NOT NULL COMMENT '账期类型：DAY/WEEK/HALF_MONTH/MONTH',
  `fin_currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '财务本位币',
  `bill_send_offset_days` int(11) NOT NULL DEFAULT '0' COMMENT '账单结束后第几天发送账单',
  `contract_node` varchar(64) DEFAULT NULL COMMENT '履约/归集节点',
  `credit_period_days` int(11) NOT NULL DEFAULT '0' COMMENT '信用期天数',
  `credit_level` varchar(32) DEFAULT NULL COMMENT '信用评级',
  `advance_limit_amount` decimal(18,4) DEFAULT NULL COMMENT '垫付/预支额度',
  `overdue_penalty_rate` decimal(10,6) DEFAULT NULL COMMENT '逾期费率',
  `effective_start_date` date NOT NULL COMMENT '生效开始日期',
  `effective_end_date` date DEFAULT NULL COMMENT '生效结束日期',
  `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态：1启用，0停用',
  `version` int(11) NOT NULL DEFAULT '1' COMMENT '版本号',
  `is_current_version` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否当前版本',
  `extra_json` json COMMENT '扩展配置JSON',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0否，1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bill_config_version` (`config_no`,`version`),
  KEY `idx_bill_config_customer` (`sc_id`,`shop_id`,`user_id`,`member_code`,`status`,`is_deleted`),
  KEY `idx_bill_config_current` (`sc_id`,`shop_id`,`user_id`,`member_code`,`config_type`,`is_current_version`,`is_deleted`),
  KEY `idx_bill_config_parent` (`parent_config_id`,`config_type`,`priority`,`status`,`is_deleted`),
  KEY `idx_bill_config_effective` (`effective_start_date`,`effective_end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='账号/账单配置：默认配置/目的国仓库分支配置';

CREATE TABLE `bill_config_scope` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `bill_config_id` bigint(20) unsigned NOT NULL COMMENT '账单配置ID',
  `scope_type` varchar(32) NOT NULL COMMENT '限定类型：DEST_COUNTRY集运目的国，WAREHOUSE集运仓',
  `scope_code` varchar(64) NOT NULL COMMENT '限定值编码',
  `scope_name` varchar(128) DEFAULT NULL COMMENT '限定值名称',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_config_scope` (`bill_config_id`,`scope_type`,`scope_code`),
  KEY `idx_scope_lookup` (`scope_type`,`scope_code`,`bill_config_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='账单配置限定范围';

CREATE TABLE `business_type_fee_index` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `business_type_code` varchar(64) NOT NULL COMMENT '业务类型编码：PEER同行订单，ECOMMERCE电商订单，CONSOLIDATION集运订单',
  `business_type_name` varchar(128) NOT NULL COMMENT '业务类型名称',
  `fee_index_id` bigint(20) unsigned NOT NULL COMMENT '费项索引ID',
  `fee_source_rule_id` bigint(20) unsigned NOT NULL COMMENT '费项数据来源规则ID',
  `fee_code` varchar(64) NOT NULL COMMENT '费项编码快照',
  `fee_name` varchar(128) NOT NULL COMMENT '费项名称快照',
  `fee_type` varchar(16) NOT NULL COMMENT '费用类型：AR/ARD/AP/ARAP',
  `priority` int(11) NOT NULL DEFAULT '0' COMMENT '业务类型内归集优先级',
  `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  `extra_json` json COMMENT '扩展配置JSON',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_business_fee_rule` (`business_type_code`,`fee_index_id`,`fee_source_rule_id`),
  KEY `idx_business_fee_enabled` (`business_type_code`,`enabled`,`priority`),
  KEY `idx_business_fee_rule` (`fee_source_rule_id`),
  KEY `idx_business_fee_index` (`fee_index_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='业务类型关联费项';

CREATE TABLE `bill_config_fee_currency_rule` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `bill_config_id` bigint(20) unsigned NOT NULL COMMENT '账单配置ID',
  `business_type_code` varchar(64) NOT NULL COMMENT '业务类型编码',
  `fee_index_id` bigint(20) unsigned DEFAULT NULL COMMENT '费项索引ID',
  `fee_code` varchar(64) NOT NULL COMMENT '费项编码',
  `fee_name` varchar(128) DEFAULT NULL COMMENT '费项名称',
  `charge_currency_mode` varchar(32) NOT NULL DEFAULT 'CONFIG_DEFAULT' COMMENT '收费币种模式：CONFIG_DEFAULT账单默认币种，SOURCE来源币种，FIXED固定币种',
  `charge_currency` varchar(16) DEFAULT NULL COMMENT '固定收费币种',
  `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用：0否，1是',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除：0否，1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bill_config_fee_currency` (`bill_config_id`,`business_type_code`,`fee_code`),
  KEY `idx_bill_config_currency_rule` (`bill_config_id`,`enabled`,`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='账单配置费项收费币种规则';


CREATE TABLE `bill_generate_task` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `task_no` varchar(64) NOT NULL COMMENT '任务编号',
  `bill_config_id` bigint(20) unsigned NOT NULL COMMENT '账单配置ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员/客户编码',
  `billing_period_start_date` date NOT NULL COMMENT '账期开始日期',
  `billing_period_end_date` date NOT NULL COMMENT '账期结束日期',
  `task_status` varchar(32) NOT NULL COMMENT '任务状态：INIT/RUNNING/SUCCESS/FAILED/CANCELED',
  `trigger_type` varchar(32) NOT NULL DEFAULT 'SCHEDULE' COMMENT '触发方式：SCHEDULE/MANUAL/RETRY',
  `idempotent_key` varchar(128) NOT NULL COMMENT '任务幂等键',
  `retry_count` int(11) NOT NULL DEFAULT '0' COMMENT '重试次数',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '结束时间',
  `duration_ms` bigint(20) NOT NULL DEFAULT '0' COMMENT '执行耗时毫秒',
  `pulled_order_count` int(11) NOT NULL DEFAULT '0' COMMENT '拉取订单数',
  `matched_order_count` int(11) NOT NULL DEFAULT '0' COMMENT '命中出账订单数',
  `skipped_order_count` int(11) NOT NULL DEFAULT '0' COMMENT '跳过订单数',
  `fee_detail_count` int(11) NOT NULL DEFAULT '0' COMMENT '生成费用明细数',
  `additional_fee_count` int(11) NOT NULL DEFAULT '0' COMMENT '生成附加费明细数',
  `failed_count` int(11) NOT NULL DEFAULT '0' COMMENT '失败数据数',
  `receivable_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '本任务生成应收金额',
  `error_message` varchar(2000) DEFAULT NULL COMMENT '错误信息',
  `bill_config_snapshot_json` json COMMENT '账单配置快照JSON',
  `bill_scope_snapshot_json` json COMMENT '账单配置范围快照JSON',
  `fee_rule_snapshot_json` json COMMENT '费项规则快照JSON',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_idempotent` (`idempotent_key`),
  UNIQUE KEY `uk_task_period` (`bill_config_id`,`billing_period_start_date`,`billing_period_end_date`,`trigger_type`),
  KEY `idx_task_status` (`task_status`,`created_at`),
  KEY `idx_task_subject_period` (`sc_id`,`shop_id`,`user_id`,`member_code`,`billing_period_start_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='账单生成任务';

CREATE TABLE `main_order` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员/客户编码',
  `order_no` varchar(64) NOT NULL COMMENT '业务主单号',
  `order_type` varchar(64) NOT NULL COMMENT '业务主单类型',
  `order_source` varchar(64) DEFAULT NULL COMMENT '订单来源',
  `order_status` varchar(64) DEFAULT NULL COMMENT '订单状态',
  `customer_name` varchar(128) DEFAULT NULL COMMENT '客户/会员名称',
  `store_name` varchar(128) DEFAULT NULL COMMENT '店铺名称',
  `recipient` varchar(128) DEFAULT NULL COMMENT '收件人/申报人',
  `is_tax_included` tinyint(1) DEFAULT NULL COMMENT '是否含税',
  `cargo_type` varchar(64) DEFAULT NULL COMMENT '货物类型',
  `shipping_warehouse` varchar(128) DEFAULT NULL COMMENT '发运仓',
  `timeliness_type` varchar(64) DEFAULT NULL COMMENT '时效类型',
  `destination_country` varchar(64) DEFAULT NULL COMMENT '目的国',
  `last_mile_carrier` varchar(128) DEFAULT NULL COMMENT '尾程承运商',
  `last_mile_waybill_no` varchar(64) DEFAULT NULL COMMENT '尾程运单号',
  `first_mile_waybill_no` varchar(64) DEFAULT NULL COMMENT '首程运单号',
  `route_auto_billing_scheme_no` varchar(128) DEFAULT NULL COMMENT '线路自动计费方案编号',
  `total_receivable` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '总应收',
  `total_cost` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '总成本',
  `total_profit` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '总利润',
  `bill_id` bigint(20) unsigned DEFAULT NULL COMMENT '归属账单ID',
  `bill_no` varchar(64) DEFAULT NULL COMMENT '归属账单编号',
  `bill_config_id` bigint(20) unsigned DEFAULT NULL COMMENT '账单配置ID',
  `config_type` varchar(16) DEFAULT NULL COMMENT '账单配置类型：DEFAULT默认配置，BRANCH分支配置',
  `generate_task_id` bigint(20) unsigned DEFAULT NULL COMMENT '账单生成任务ID',
  `billing_period_start_date` date DEFAULT NULL COMMENT '归属账单账期开始日期',
  `billing_period_end_date` date DEFAULT NULL COMMENT '归属账单账期结束日期',
  `bill_currency` varchar(16) DEFAULT NULL COMMENT '归属账单结算币种',
  `fin_currency` varchar(16) DEFAULT NULL COMMENT '财务本位币',
  `billed_at` datetime DEFAULT NULL COMMENT '计入账单时间',
  `order_created_at` datetime DEFAULT NULL COMMENT '业务单创建时间',
  `billing_node_time` datetime DEFAULT NULL COMMENT '到达计费节点时间',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_main_order_no` (`order_no`),
  KEY `idx_main_order_subject` (`sc_id`,`shop_id`,`user_id`,`member_code`,`order_created_at`),
  KEY `idx_main_order_waybill` (`last_mile_waybill_no`),
  KEY `idx_main_order_first_waybill` (`first_mile_waybill_no`),
  KEY `idx_main_order_billing_node` (`billing_node_time`),
  KEY `idx_main_order_bill` (`bill_id`,`bill_no`),
  KEY `idx_main_order_task` (`generate_task_id`),
  KEY `idx_main_order_bill_period` (`bill_config_id`,`billing_period_start_date`,`billing_period_end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='业务主单快照';

CREATE TABLE `ar_bill` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `bill_no` varchar(64) NOT NULL COMMENT '账单编号',
  `bill_title` varchar(128) NOT NULL COMMENT '账单标题',
  `bill_status` varchar(32) NOT NULL COMMENT '账单状态：DRAFT/GENERATED/CONFIRMED/PART_PAID/PAID/VOID',
  `bill_config_id` bigint(20) unsigned NOT NULL COMMENT '账单配置ID',
  `config_type` varchar(16) NOT NULL COMMENT '配置类型：DEFAULT默认配置，BRANCH分支配置',
  `generate_task_id` bigint(20) unsigned DEFAULT NULL COMMENT '生成任务ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员/客户编码',
  `member_name` varchar(128) DEFAULT NULL COMMENT '会员/客户名称',
  `customer_no` varchar(64) DEFAULT NULL COMMENT '外部客户编号',
  `customer_name` varchar(128) DEFAULT NULL COMMENT '外部客户名称',
  `destination_country` varchar(64) DEFAULT NULL COMMENT '集运目的国',
  `consolidation_warehouse_code` varchar(64) DEFAULT NULL COMMENT '集运仓编码',
  `billing_cycle_type` varchar(32) NOT NULL COMMENT '账期类型',
  `billing_period_start_date` date NOT NULL COMMENT '账期开始日期',
  `billing_period_end_date` date NOT NULL COMMENT '账期结束日期',
  `bill_send_date` date DEFAULT NULL COMMENT '账单发送日',
  `credit_period_end_date` date DEFAULT NULL COMMENT '信用期结束日',
  `payment_overdue_days` int(11) NOT NULL DEFAULT '0' COMMENT '付款逾期天数',
  `bill_currency` varchar(16) NOT NULL COMMENT '账单结算币种',
  `fin_currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '财务本位币',
  `initial_receivable_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '初始应收金额<账单币种>',
  `this_adjustment_delta_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '本期调整增量<账单币种>',
  `previous_adjustment_delta_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '往期调整增量<账单币种>',
  `late_fee_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '滞纳金<账单币种>',
  `receivable_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '应收金额<账单币种>',
  `paid_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '已核销金额<账单币种>',
  `unpaid_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '未核销金额<账单币种>',
  `receivable_amount_fin` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '应收金额<本位币>',
  `paid_amount_fin` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '已核销金额<本位币>',
  `confirmed_at` datetime DEFAULT NULL COMMENT '确认时间',
  `confirmed_by` varchar(64) DEFAULT NULL COMMENT '确认人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除：0否，1是',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ar_bill_no` (`bill_no`),
  UNIQUE KEY `uk_ar_bill_period` (`bill_config_id`,`billing_period_start_date`,`billing_period_end_date`),
  KEY `idx_ar_bill_customer_status` (`sc_id`,`shop_id`,`user_id`,`member_code`,`bill_status`,`is_deleted`),
  KEY `idx_ar_bill_config_type` (`bill_config_id`,`config_type`),
  KEY `idx_ar_bill_country_wh` (`destination_country`,`consolidation_warehouse_code`),
  KEY `idx_ar_bill_period` (`billing_period_start_date`,`billing_period_end_date`),
  KEY `idx_ar_bill_customer_no` (`customer_no`),
  KEY `idx_ar_bill_task` (`generate_task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='应收账单';

CREATE TABLE `ar_bill_currency_summary` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `bill_id` bigint(20) unsigned NOT NULL COMMENT '账单ID',
  `bill_no` varchar(64) NOT NULL COMMENT '账单编号',
  `currency` varchar(16) NOT NULL COMMENT '收费币种',
  `receivable_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '应收金额',
  `paid_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '已核销金额',
  `unpaid_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '未核销金额',
  `fee_count` int(11) NOT NULL DEFAULT '0' COMMENT '费用明细数',
  `order_count` int(11) NOT NULL DEFAULT '0' COMMENT '涉及订单数',
  `summary_status` varchar(32) NOT NULL DEFAULT 'WAITING_PAY' COMMENT '币种核销状态：WAITING_PAY待收款，PART_PAID部分核销，PAID已核销',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bill_currency_summary` (`bill_no`,`currency`),
  KEY `idx_currency_summary_bill` (`bill_id`),
  KEY `idx_currency_summary_status` (`currency`,`summary_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='应收账单按币种汇总';

CREATE TABLE `fee_detail` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `fee_no` varchar(64) NOT NULL COMMENT '费用编号',
  `bill_id` bigint(20) unsigned NOT NULL COMMENT '账单ID',
  `bill_no` varchar(64) NOT NULL COMMENT '账单编号',
  `bill_config_id` bigint(20) unsigned NOT NULL COMMENT '账单配置ID',
  `business_type_code` varchar(64) DEFAULT NULL COMMENT '命中的业务类型编码',
  `business_type_fee_id` bigint(20) unsigned DEFAULT NULL COMMENT '命中的业务类型费项关联ID',
  `generate_task_id` bigint(20) unsigned DEFAULT NULL COMMENT '生成任务ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员/客户编码',
  `fee_index_id` bigint(20) unsigned NOT NULL COMMENT '费项索引ID',
  `fee_source_rule_id` bigint(20) unsigned DEFAULT NULL COMMENT '费项数据来源规则ID',
  `fee_code` varchar(64) NOT NULL COMMENT '费项编码',
  `fee_name` varchar(128) NOT NULL COMMENT '费项名称',
  `fee_type` varchar(16) NOT NULL COMMENT '费用类型：AR/ARD/AP/ARAP',
  `attached_object` varchar(16) NOT NULL COMMENT '挂靠对象：BILL/ORDER/LAST_PACKAGE/FIRST_PACKAGE',
  `business_order_no` varchar(64) DEFAULT NULL COMMENT '业务主单号',
  `destination_country` varchar(64) DEFAULT NULL COMMENT '集运目的国',
  `consolidation_warehouse_code` varchar(64) DEFAULT NULL COMMENT '集运仓编码',
  `last_mile_waybill_no` varchar(64) DEFAULT NULL COMMENT '尾程运单号',
  `first_mile_waybill_no` varchar(64) DEFAULT NULL COMMENT '首程运单号',
  `source_system` varchar(64) NOT NULL COMMENT '来源系统',
  `source_table` varchar(128) NOT NULL COMMENT '来源表',
  `source_id` varchar(128) NOT NULL COMMENT '来源数据ID',
  `source_order_id` varchar(128) DEFAULT NULL COMMENT '来源业务主单ID',
  `source_bill_no` varchar(128) DEFAULT NULL COMMENT '来源财务账单号',
  `source_biz_no` varchar(128) DEFAULT NULL COMMENT '来源业务单号',
  `source_fee_field` varchar(128) DEFAULT NULL COMMENT '来源金额字段',
  `source_fee_time` datetime DEFAULT NULL COMMENT '来源费用发生时间',
  `source_pay_status` varchar(64) DEFAULT NULL COMMENT '来源费用支付状态',
  `source_row_hash` varchar(64) DEFAULT NULL COMMENT '来源关键字段哈希，用于检测来源数据变化',
  `source_extra_json` json COMMENT '来源扩展快照JSON',
  `dedupe_key` varchar(255) NOT NULL COMMENT '费用幂等键',
  `fee_currency` varchar(16) NOT NULL COMMENT '费用原始币种',
  `amount_fee_currency` decimal(18,4) NOT NULL COMMENT '费用金额<原始币种>',
  `exchange_rate_to_bill` decimal(18,8) DEFAULT NULL COMMENT '原始币种到账单币种汇率',
  `exchange_rate_level_to_bill` varchar(16) DEFAULT NULL COMMENT '汇率级别',
  `bill_currency` varchar(16) NOT NULL COMMENT '账单币种',
  `amount_bill_currency` decimal(18,4) NOT NULL COMMENT '费用金额<账单币种>',
  `exchange_rate_to_fin` decimal(18,8) DEFAULT NULL COMMENT '账单币种到本位币汇率',
  `exchange_rate_level_to_fin` varchar(16) DEFAULT NULL COMMENT '汇率级别',
  `fin_currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '财务本位币',
  `amount_fin_currency` decimal(18,4) NOT NULL COMMENT '费用金额<本位币>',
  `fee_status` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '费用状态：NORMAL/ADJUSTED/REVERSED/VOID',
  `manual_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否手工补录：0否，1是',
  `manual_reason` varchar(500) DEFAULT NULL COMMENT '手工补录原因',
  `original_fee_id` bigint(20) unsigned DEFAULT NULL COMMENT '原费用ID，红冲/调账时使用',
  `offset_bill_no` varchar(64) DEFAULT NULL COMMENT '对冲账单号',
  `voucher_url` varchar(500) DEFAULT NULL COMMENT '费用凭证URL',
  `voucher_supplier` varchar(128) DEFAULT NULL COMMENT '费用凭证供应商',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fee_no` (`fee_no`),
  UNIQUE KEY `uk_fee_dedupe` (`dedupe_key`),
  KEY `idx_fee_bill` (`bill_id`,`fee_type`,`fee_status`),
  KEY `idx_fee_config` (`bill_config_id`,`fee_code`),
  KEY `idx_fee_business_type` (`business_type_code`,`business_type_fee_id`),
  KEY `idx_fee_country_wh` (`destination_country`,`consolidation_warehouse_code`),
  KEY `idx_fee_subject_time` (`sc_id`,`shop_id`,`user_id`,`member_code`,`source_fee_time`),
  KEY `idx_fee_order` (`business_order_no`),
  KEY `idx_fee_last_waybill` (`last_mile_waybill_no`),
  KEY `idx_fee_first_waybill` (`first_mile_waybill_no`),
  KEY `idx_fee_source` (`source_system`,`source_table`,`source_id`),
  KEY `idx_fee_source_rule` (`fee_source_rule_id`),
  KEY `idx_fee_original` (`original_fee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='费用详情/费用快照';

CREATE TABLE `bill_source_collect_mark` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `collect_no` varchar(64) NOT NULL COMMENT '归集标记编号',
  `collect_type` varchar(32) NOT NULL COMMENT '归集类型：MAIN_ORDER主订单，ADDITIONAL_FEE附加费，ADDITIONAL_INCREMENT附加费增量',
  `source_system` varchar(64) NOT NULL COMMENT '来源系统，如OFP',
  `source_database` varchar(64) DEFAULT NULL COMMENT '来源库',
  `source_table` varchar(128) NOT NULL COMMENT '来源表',
  `source_id` varchar(128) NOT NULL COMMENT '来源数据ID',
  `source_biz_no` varchar(128) DEFAULT NULL COMMENT '来源业务单号',
  `source_order_id` varchar(128) DEFAULT NULL COMMENT '来源订单ID',
  `source_order_no` varchar(128) DEFAULT NULL COMMENT '来源订单号',
  `bill_id` bigint(20) unsigned NOT NULL COMMENT '账单ID',
  `bill_no` varchar(64) NOT NULL COMMENT '账单编号',
  `bill_config_id` bigint(20) unsigned NOT NULL COMMENT '账单配置ID',
  `generate_task_id` bigint(20) unsigned DEFAULT NULL COMMENT '生成任务ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员/客户编码',
  `mark_status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '源表打标状态：PENDING待打标，MARKED已打标，FAILED打标失败',
  `marked_at` datetime DEFAULT NULL COMMENT '源表打标成功时间',
  `retry_count` int(11) NOT NULL DEFAULT '0' COMMENT '打标重试次数',
  `last_retry_at` datetime DEFAULT NULL COMMENT '最近重试时间',
  `last_error_message` varchar(2000) DEFAULT NULL COMMENT '最近失败原因',
  `source_snapshot_json` json COMMENT '来源数据关键字段快照',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_collect_no` (`collect_no`),
  UNIQUE KEY `uk_source_collect` (`source_system`,`source_table`,`source_id`,`collect_type`),
  KEY `idx_collect_bill` (`bill_id`,`collect_type`,`mark_status`),
  KEY `idx_collect_task` (`generate_task_id`,`mark_status`),
  KEY `idx_collect_subject` (`sc_id`,`shop_id`,`user_id`,`member_code`,`mark_status`),
  KEY `idx_collect_source_order` (`source_order_id`,`source_order_no`),
  KEY `idx_collect_retry` (`mark_status`,`retry_count`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='账单来源归集标记/跨库打标补偿记录';

CREATE TABLE `bill_exchange_rate` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `bill_id` bigint(20) unsigned NOT NULL COMMENT '账单ID',
  `bill_no` varchar(64) NOT NULL COMMENT '账单编号',
  `bill_currency` varchar(16) NOT NULL COMMENT '账单结算币种',
  `conversion_currency` varchar(16) NOT NULL COMMENT '换算币种',
  `conversion_currency_type` varchar(32) NOT NULL COMMENT '换算币种类型：FEE/FIN',
  `conversion_direction` varchar(8) NOT NULL COMMENT '换算方向：MUL/DIV',
  `exchange_rate` decimal(18,8) NOT NULL COMMENT '锁定汇率',
  `rate_date` date DEFAULT NULL COMMENT '汇率日期',
  `rate_source` varchar(64) DEFAULT NULL COMMENT '汇率来源',
  `source_type` varchar(16) NOT NULL DEFAULT 'SYSTEM' COMMENT '来源：SYSTEM系统，MANUAL人工',
  `edit_reason` varchar(500) DEFAULT NULL COMMENT '人工编辑原因',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bill_rate` (`bill_id`,`bill_currency`,`conversion_currency`,`conversion_currency_type`),
  KEY `idx_bill_rate_no` (`bill_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='账单汇率';

CREATE TABLE `fee_adjustment_order` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `adjustment_no` varchar(64) NOT NULL COMMENT '调账/红冲单号',
  `adjustment_type` varchar(32) NOT NULL COMMENT '类型：ADJUST调账，REVERSAL红冲',
  `adjustment_period_type` varchar(16) NOT NULL DEFAULT 'CURRENT' COMMENT '调账账期类型：CURRENT本期，PREVIOUS往期',
  `trigger_bill_id` bigint(20) unsigned NOT NULL COMMENT '触发账单ID',
  `trigger_bill_no` varchar(64) NOT NULL COMMENT '触发账单编号',
  `source_bill_no` varchar(64) DEFAULT NULL COMMENT '来源账单编号',
  `target_bill_no` varchar(64) DEFAULT NULL COMMENT '计入目标账单编号',
  `source_bill_config_id` bigint(20) unsigned DEFAULT NULL COMMENT '来源账单配置ID',
  `source_main_order_id` bigint(20) unsigned DEFAULT NULL COMMENT '来源BMS订单快照ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员/客户编码',
  `adjustment_status` varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态：DRAFT/SUBMITTED/APPROVED/REJECTED/POSTED/VOID',
  `adjustment_currency` varchar(16) NOT NULL COMMENT '调账币种',
  `adjustment_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '调账总金额',
  `rebuild_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否重整生成：0否，1是',
  `import_batch_no` varchar(64) DEFAULT NULL COMMENT '导入批次号',
  `original_amount` decimal(18,4) DEFAULT NULL COMMENT '原金额',
  `rebuilt_amount` decimal(18,4) DEFAULT NULL COMMENT '重整后金额',
  `reason` varchar(500) DEFAULT NULL COMMENT '原因',
  `voucher_url` varchar(500) DEFAULT NULL COMMENT '凭证URL',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `approved_at` datetime DEFAULT NULL COMMENT '审核时间',
  `approved_by` varchar(64) DEFAULT NULL COMMENT '审核人',
  `posted_at` datetime DEFAULT NULL COMMENT '入账时间',
  `posted_by` varchar(64) DEFAULT NULL COMMENT '入账人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_adjustment_no` (`adjustment_no`),
  KEY `idx_adjustment_bill` (`trigger_bill_id`),
  KEY `idx_adjustment_source_bill` (`source_bill_no`,`target_bill_no`),
  KEY `idx_adjustment_period` (`trigger_bill_no`,`adjustment_period_type`,`adjustment_status`),
  KEY `idx_adjustment_subject` (`sc_id`,`shop_id`,`user_id`,`member_code`,`adjustment_status`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='费用调账/红冲单';


CREATE TABLE `payment_receipt` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `receipt_no` varchar(64) NOT NULL COMMENT '收款单号',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员/客户编码',
  `payer_name` varchar(128) DEFAULT NULL COMMENT '付款方名称',
  `payment_channel` varchar(64) DEFAULT NULL COMMENT '收款渠道',
  `receipt_currency` varchar(16) NOT NULL COMMENT '收款币种',
  `receipt_amount` decimal(18,4) NOT NULL COMMENT '收款金额',
  `writeoff_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '已核销金额<收款币种>',
  `unwriteoff_amount` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '未核销金额<收款币种>',
  `receipt_status` varchar(32) NOT NULL DEFAULT 'SUBMITTED' COMMENT '状态：SUBMITTED/CONFIRMED/PART_WRITEOFF/WRITEOFF/VOID',
  `voucher_url` varchar(500) DEFAULT NULL COMMENT '付款凭证URL',
  `submitted_at` datetime DEFAULT NULL COMMENT '提交时间',
  `paid_at` datetime DEFAULT NULL COMMENT '实际付款时间',
  `confirmed_at` datetime DEFAULT NULL COMMENT '确认收款时间',
  `confirmed_by` varchar(64) DEFAULT NULL COMMENT '确认人',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_receipt_no` (`receipt_no`),
  KEY `idx_receipt_subject_status` (`sc_id`,`shop_id`,`user_id`,`member_code`,`receipt_status`,`created_at`),
  KEY `idx_receipt_paid_at` (`paid_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='收款记录';

CREATE TABLE `payment_writeoff_detail` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `writeoff_no` varchar(64) NOT NULL COMMENT '核销流水号',
  `receipt_id` bigint(20) unsigned NOT NULL COMMENT '收款单ID',
  `receipt_no` varchar(64) NOT NULL COMMENT '收款单号',
  `bill_id` bigint(20) unsigned NOT NULL COMMENT '账单ID',
  `bill_no` varchar(64) NOT NULL COMMENT '账单编号',
  `currency_summary_id` bigint(20) unsigned DEFAULT NULL COMMENT '核销的账单币种汇总ID',
  `settlement_currency` varchar(16) DEFAULT NULL COMMENT '本次核销结算币种',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链/组织ID',
  `shop_id` bigint(20) NOT NULL COMMENT '店铺ID',
  `user_id` bigint(20) NOT NULL COMMENT '用户ID',
  `member_code` varchar(64) NOT NULL COMMENT '会员/客户编码',
  `receipt_currency` varchar(16) NOT NULL COMMENT '收款币种',
  `writeoff_amount_receipt_currency` decimal(18,4) NOT NULL COMMENT '核销金额<收款币种>',
  `bill_currency` varchar(16) NOT NULL COMMENT '账单币种',
  `exchange_rate_to_bill` decimal(18,8) DEFAULT NULL COMMENT '收款币种到账单币种汇率',
  `writeoff_amount_bill_currency` decimal(18,4) NOT NULL COMMENT '核销金额<账单币种>',
  `fin_currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '财务本位币',
  `exchange_rate_to_fin` decimal(18,8) DEFAULT NULL COMMENT '账单币种到本位币汇率',
  `writeoff_amount_fin_currency` decimal(18,4) NOT NULL COMMENT '核销金额<本位币>',
  `writeoff_status` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '核销状态：NORMAL/REVERSED/VOID',
  `writeoff_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '核销时间',
  `writeoff_by` varchar(64) DEFAULT NULL COMMENT '核销人',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_writeoff_no` (`writeoff_no`),
  KEY `idx_writeoff_currency_summary` (`currency_summary_id`),
  KEY `idx_writeoff_receipt` (`receipt_id`),
  KEY `idx_writeoff_bill` (`bill_id`),
  KEY `idx_writeoff_subject_time` (`sc_id`,`shop_id`,`user_id`,`member_code`,`writeoff_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='收款核销明细';

CREATE TABLE `bms_operation_log` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `biz_type` varchar(64) NOT NULL COMMENT '业务类型',
  `biz_id` varchar(64) NOT NULL COMMENT '业务ID',
  `operation_type` varchar(64) NOT NULL COMMENT '操作类型',
  `before_json` json COMMENT '操作前JSON',
  `after_json` json COMMENT '操作后JSON',
  `operator_id` varchar(64) DEFAULT NULL COMMENT '操作人ID',
  `operator_name` varchar(128) DEFAULT NULL COMMENT '操作人名称',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_operation_biz` (`biz_type`,`biz_id`,`created_at`),
  KEY `idx_operation_operator` (`operator_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='BMS操作日志';

INSERT INTO `fee_source_datasource` (
  `datasource_code`, `datasource_name`, `source_system`, `env_code`, `db_type`, `driver_class_name`,
  `jdbc_url`, `username`, `password_cipher`, `password_mask`, `default_database`, `default_schema`,
  `enabled`, `max_pool_size`, `connect_timeout_seconds`, `query_timeout_seconds`, `max_rows_per_query`,
  `last_test_status`, `last_test_message`, `remark`, `created_by`, `updated_by`
) VALUES (
  'OFP_DB',
  'OFP订单库',
  'OFP',
  'PROD',
  'MYSQL',
  'com.mysql.cj.jdbc.Driver',
  'jdbc:mysql://192.168.0.250:3306/ofp_ofdb1?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false',
  'sztadmin',
  'PLEASE_SET_ENCRYPTED_PASSWORD',
  '******',
  'ofp_ofdb1',
  'ofp_ofdb1',
  1,
  5,
  10,
  30,
  50000,
  NULL,
  '初始化脚本不保存明文密码，请部署后写入加密密文',
  '集运账单费用拉取默认数据源',
  'system',
  'system'
);

SET FOREIGN_KEY_CHECKS = 1;
