-- 2026-07-27 成本账单导入与成本池初始化。
-- 仅新增独立成本域表，不复用、不修改 ar_bill、fee_detail。

CREATE TABLE IF NOT EXISTS `cost_bill` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链ID',
  `bill_no` varchar(64) NOT NULL COMMENT '成本账单编号',
  `supplier_id` bigint(20) unsigned NOT NULL COMMENT '供应商财务档案ID',
  `supplier_code_snapshot` varchar(64) NOT NULL COMMENT '供应商编码快照',
  `supplier_name_snapshot` varchar(128) NOT NULL COMMENT '供应商名称快照',
  `supplier_bill_no` varchar(128) NOT NULL COMMENT '供应商侧账单号',
  `supplier_bill_no_source` varchar(32) NOT NULL COMMENT '账单号来源：MANUAL/SYSTEM_GENERATED',
  `cost_board` varchar(32) NOT NULL COMMENT '成本板块',
  `cost_type` varchar(16) NOT NULL DEFAULT 'INDIRECT' COMMENT '成本类型；本期固定INDIRECT',
  `actual_period_start_date` date NOT NULL COMMENT '实际成本账期开始日',
  `actual_period_end_date` date NOT NULL COMMENT '实际成本账期结束日',
  `bill_date` date NOT NULL COMMENT '供应商账单落款日',
  `import_task_id` bigint(20) unsigned NOT NULL COMMENT '来源导入任务ID',
  `original_file_name` varchar(255) NOT NULL COMMENT '原始文件名',
  `original_file_url` varchar(1000) NOT NULL COMMENT '对象存储文件链接',
  `original_file_sha256` varchar(64) NOT NULL COMMENT '原始文件SHA-256',
  `original_file_size` bigint(20) unsigned NOT NULL COMMENT '原始文件字节数',
  `file_expire_at` datetime NOT NULL COMMENT '原始文件到期时间',
  `currency_count` int(11) NOT NULL DEFAULT 0 COMMENT '币种数量',
  `detail_count` int(11) NOT NULL DEFAULT 0 COMMENT '成本明细数量',
  `version` int(11) NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `created_by` varchar(64) NOT NULL COMMENT '创建人',
  `updated_by` varchar(64) NOT NULL COMMENT '最后更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_bill_sc_no` (`sc_id`, `bill_no`),
  UNIQUE KEY `uk_cost_bill_supplier_no` (`sc_id`, `supplier_id`, `supplier_bill_no`),
  UNIQUE KEY `uk_cost_bill_import_task` (`import_task_id`),
  KEY `idx_cost_bill_supplier_period` (`sc_id`, `supplier_id`, `cost_board`, `actual_period_start_date`, `actual_period_end_date`),
  KEY `idx_cost_bill_date` (`sc_id`, `bill_date`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='成本账单';

CREATE TABLE IF NOT EXISTS `cost_bill_currency_summary` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链ID',
  `cost_bill_id` bigint(20) unsigned NOT NULL COMMENT '成本账单ID',
  `cost_bill_no` varchar(64) NOT NULL COMMENT '成本账单编号',
  `currency` varchar(16) NOT NULL COMMENT '账单币种',
  `imported_amount` decimal(18,4) NOT NULL DEFAULT 0.0000 COMMENT '原始导入金额',
  `effective_amount` decimal(18,4) NOT NULL DEFAULT 0.0000 COMMENT '当前生效金额',
  `detail_count` int(11) NOT NULL DEFAULT 0 COMMENT '成本明细数量',
  `version` int(11) NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `created_by` varchar(64) NOT NULL COMMENT '创建人',
  `updated_by` varchar(64) NOT NULL COMMENT '最后更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_bill_currency` (`cost_bill_id`, `currency`),
  KEY `idx_cost_bill_currency_no` (`sc_id`, `cost_bill_no`, `currency`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='成本账单币种汇总';

CREATE TABLE IF NOT EXISTS `cost_bill_import_task` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链ID',
  `task_no` varchar(64) NOT NULL COMMENT '导入任务编号',
  `supplier_id` bigint(20) unsigned NOT NULL COMMENT '供应商财务档案ID',
  `supplier_code_snapshot` varchar(64) NOT NULL COMMENT '供应商编码快照',
  `supplier_name_snapshot` varchar(128) NOT NULL COMMENT '供应商名称快照',
  `supplier_bill_no` varchar(128) NOT NULL COMMENT '供应商侧账单号',
  `supplier_bill_no_source` varchar(32) NOT NULL COMMENT '账单号来源',
  `cost_board` varchar(32) NOT NULL COMMENT '成本板块',
  `cost_type` varchar(16) NOT NULL DEFAULT 'INDIRECT' COMMENT '成本类型；本期固定INDIRECT',
  `default_currency` varchar(16) NOT NULL COMMENT '默认币种',
  `actual_period_start_date` date NOT NULL COMMENT '实际成本账期开始日',
  `actual_period_end_date` date NOT NULL COMMENT '实际成本账期结束日',
  `bill_date` date NOT NULL COMMENT '供应商账单落款日',
  `original_file_name` varchar(255) NOT NULL COMMENT '原始文件名',
  `original_file_url` varchar(1000) NOT NULL COMMENT '对象存储文件链接',
  `original_file_sha256` varchar(64) NOT NULL COMMENT '原始文件SHA-256',
  `original_file_size` bigint(20) unsigned NOT NULL COMMENT '原始文件字节数',
  `file_expire_at` datetime NOT NULL COMMENT '原始文件到期时间',
  `file_structure_hash` varchar(64) DEFAULT NULL COMMENT '文件结构特征哈希',
  `duplicate_risk_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否疑似重复',
  `duplicate_confirmed` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否已人工确认重复风险',
  `draft_mapping_json` json DEFAULT NULL COMMENT '当前导入草稿映射',
  `confirmed_mapping_json` json DEFAULT NULL COMMENT '最终确认映射快照',
  `preview_summary_json` json DEFAULT NULL COMMENT '预览汇总',
  `task_status` varchar(32) NOT NULL COMMENT 'DRAFT/PREVIEW_READY/PENDING/RUNNING/SUCCESS/FAILED/CANCELLED',
  `failure_stage` varchar(64) DEFAULT NULL COMMENT '失败阶段',
  `failure_reason` varchar(1000) DEFAULT NULL COMMENT '失败原因',
  `reserved_bill_no` varchar(64) NOT NULL COMMENT '预留成本账单编号',
  `cost_bill_id` bigint(20) unsigned DEFAULT NULL COMMENT '成功后生成的成本账单ID',
  `cost_bill_no` varchar(64) DEFAULT NULL COMMENT '成功后生成的成本账单编号',
  `idempotency_key` varchar(128) NOT NULL COMMENT '确认导入幂等键',
  `version` int(11) NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `created_by` varchar(64) NOT NULL COMMENT '创建人',
  `updated_by` varchar(64) NOT NULL COMMENT '最后更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `confirmed_at` datetime DEFAULT NULL COMMENT '确认时间',
  `started_at` datetime DEFAULT NULL COMMENT '开始执行时间',
  `finished_at` datetime DEFAULT NULL COMMENT '完成时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_import_task_no` (`sc_id`, `task_no`),
  UNIQUE KEY `uk_cost_import_idempotency` (`sc_id`, `idempotency_key`),
  UNIQUE KEY `uk_cost_import_reserved_bill` (`sc_id`, `reserved_bill_no`),
  KEY `idx_cost_import_queue` (`task_status`, `created_at`),
  KEY `idx_cost_import_supplier_no` (`sc_id`, `supplier_id`, `supplier_bill_no`),
  KEY `idx_cost_import_file_hash` (`sc_id`, `supplier_id`, `original_file_sha256`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='成本账单导入任务';

CREATE TABLE IF NOT EXISTS `cost_import_setting_snapshot` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链ID',
  `supplier_id` bigint(20) unsigned NOT NULL COMMENT '供应商财务档案ID',
  `cost_board` varchar(32) NOT NULL COMMENT '成本板块',
  `file_structure_hash` varchar(64) NOT NULL COMMENT '文件结构特征哈希',
  `file_structure_json` json NOT NULL COMMENT '工作表和表头结构特征',
  `sheet_range_json` json NOT NULL COMMENT '工作表数据范围配置',
  `scattered_value_json` json DEFAULT NULL COMMENT '零散金额字段配置',
  `business_field_mapping_json` json DEFAULT NULL COMMENT '业务字段映射',
  `amount_mapping_json` json NOT NULL COMMENT '金额、币种和方向映射',
  `fee_mapping_json` json NOT NULL COMMENT '原始费项到标准成本费项映射',
  `latest_import_task_id` bigint(20) unsigned NOT NULL COMMENT '最近导入任务ID',
  `version` int(11) NOT NULL DEFAULT 1 COMMENT '快照版本号',
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `created_by` varchar(64) NOT NULL COMMENT '创建人',
  `updated_by` varchar(64) NOT NULL COMMENT '最后更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_import_snapshot` (`sc_id`, `supplier_id`, `cost_board`, `file_structure_hash`),
  KEY `idx_cost_import_snapshot_task` (`sc_id`, `latest_import_task_id`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='成本账单导入设置快照';

CREATE TABLE IF NOT EXISTS `cost_import_raw_row` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链ID',
  `import_task_id` bigint(20) unsigned NOT NULL COMMENT '导入任务ID',
  `sheet_name` varchar(128) NOT NULL COMMENT '工作表名称',
  `row_no` int(11) NOT NULL COMMENT 'Excel原始行号',
  `raw_data_json` json NOT NULL COMMENT '原始字段快照',
  `row_hash` varchar(64) NOT NULL COMMENT '原始行特征哈希',
  `row_status` varchar(32) NOT NULL COMMENT 'INCLUDED/EXCLUDED',
  `exclude_reason` varchar(500) DEFAULT NULL COMMENT '排除原因',
  `expire_at` datetime NOT NULL COMMENT '原始行到期时间',
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `created_by` varchar(64) NOT NULL COMMENT '创建人',
  `updated_by` varchar(64) NOT NULL COMMENT '最后更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_raw_row` (`import_task_id`, `sheet_name`, `row_no`),
  KEY `idx_cost_raw_hash` (`sc_id`, `row_hash`),
  KEY `idx_cost_raw_expire` (`expire_at`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='成本账单导入原始行';

CREATE TABLE IF NOT EXISTS `cost_detail` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `sc_id` bigint(20) NOT NULL COMMENT '供应链ID',
  `cost_detail_no` varchar(64) NOT NULL COMMENT '成本明细编号',
  `cost_bill_id` bigint(20) unsigned NOT NULL COMMENT '成本账单ID',
  `cost_bill_no` varchar(64) NOT NULL COMMENT '成本账单编号',
  `import_task_id` bigint(20) unsigned NOT NULL COMMENT '导入任务ID',
  `raw_row_id` bigint(20) unsigned NOT NULL COMMENT '原始行ID',
  `sheet_name` varchar(128) NOT NULL COMMENT '工作表名称快照',
  `source_row_no` int(11) NOT NULL COMMENT 'Excel原始行号',
  `source_amount_column` varchar(128) NOT NULL COMMENT '来源金额字段',
  `key_no_type` varchar(32) DEFAULT NULL COMMENT '关键单号类型；为空表示未选择关键单号',
  `key_no` varchar(255) DEFAULT NULL COMMENT '供应商原始关键单号',
  `supplier_id` bigint(20) unsigned NOT NULL COMMENT '供应商财务档案ID',
  `supplier_code_snapshot` varchar(64) NOT NULL COMMENT '供应商编码快照',
  `supplier_name_snapshot` varchar(128) NOT NULL COMMENT '供应商名称快照',
  `supplier_bill_no` varchar(128) NOT NULL COMMENT '供应商侧账单号',
  `cost_board` varchar(32) NOT NULL COMMENT '成本板块',
  `actual_period_start_date` date NOT NULL COMMENT '实际成本账期开始日',
  `actual_period_end_date` date NOT NULL COMMENT '实际成本账期结束日',
  `source_fee_name` varchar(255) NOT NULL COMMENT '供应商原始费项名称',
  `cost_fee_index_id` bigint(20) unsigned NOT NULL COMMENT '成本费项索引ID',
  `cost_fee_code_snapshot` varchar(64) NOT NULL COMMENT '标准成本费项编码快照',
  `cost_fee_name_snapshot` varchar(128) NOT NULL COMMENT '标准成本费项名称快照',
  `mapping_method` varchar(32) NOT NULL COMMENT 'SNAPSHOT/AUTO_SUGGEST/MANUAL',
  `mapping_confirmed_by` varchar(64) NOT NULL COMMENT '映射确认人',
  `mapping_confirmed_at` datetime NOT NULL COMMENT '映射确认时间',
  `currency` varchar(16) NOT NULL COMMENT '成本币种',
  `amount_direction` varchar(16) NOT NULL COMMENT '金额方向：POSITIVE/NEGATIVE',
  `imported_amount` decimal(18,4) NOT NULL COMMENT '有符号原始导入金额',
  `effective_amount` decimal(18,4) NOT NULL COMMENT '当前生效金额',
  `cost_type` varchar(16) NOT NULL DEFAULT 'INDIRECT' COMMENT '成本类型；本期固定INDIRECT',
  `version` int(11) NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0正常 1删除',
  `created_by` varchar(64) NOT NULL COMMENT '创建人',
  `updated_by` varchar(64) NOT NULL COMMENT '最后更新人',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_detail_no` (`sc_id`, `cost_detail_no`),
  UNIQUE KEY `uk_cost_detail_source` (`import_task_id`, `raw_row_id`, `source_amount_column`, `cost_fee_index_id`),
  KEY `idx_cost_detail_bill` (`sc_id`, `cost_bill_id`, `is_deleted`),
  KEY `idx_cost_detail_supplier_period` (`sc_id`, `supplier_id`, `actual_period_start_date`, `actual_period_end_date`),
  KEY `idx_cost_detail_fee_currency` (`sc_id`, `cost_fee_index_id`, `currency`, `is_deleted`),
  KEY `idx_cost_detail_key_no` (`sc_id`, `key_no_type`, `key_no`, `is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='成本池明细';
