CREATE TABLE `bill_fee_detail_relation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `relation_no` varchar(64) NOT NULL COMMENT '关系编号',
  `bill_id` bigint NOT NULL COMMENT '账单ID',
  `bill_no` varchar(64) NOT NULL COMMENT '账单编号',
  `bill_type` varchar(32) NOT NULL DEFAULT 'AR' COMMENT '账单类型',
  `bill_config_id` bigint DEFAULT NULL COMMENT '账单配置ID',
  `generate_task_id` bigint DEFAULT NULL COMMENT '生成任务ID',
  `fee_detail_id` bigint NOT NULL COMMENT '来源费用ID',
  `fee_index_id` bigint DEFAULT NULL COMMENT '费项索引ID',
  `fee_code` varchar(64) DEFAULT NULL COMMENT '费项编码',
  `relation_type` varchar(32) NOT NULL COMMENT '关系类型：NORMAL/ADJUSTMENT/REVERSAL',
  `relation_status` varchar(32) NOT NULL COMMENT '关系状态：ACTIVE/REPLACED/REVERSED/VOID',
  `settlement_role` varchar(32) NOT NULL COMMENT '结算角色：RECEIVABLE/PAYABLE/REFUND',
  `fee_currency` varchar(16) NOT NULL COMMENT '来源费用币种',
  `amount_fee_currency` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '来源费用金额',
  `bill_currency` varchar(16) NOT NULL COMMENT '账单币种',
  `amount_bill_currency` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '账单金额',
  `fin_currency` varchar(16) DEFAULT NULL COMMENT '财务本位币',
  `amount_fin_currency` decimal(18,4) NOT NULL DEFAULT '0.0000' COMMENT '财务本位币金额',
  `exchange_rate_to_bill` decimal(18,8) DEFAULT NULL COMMENT '来源费用转账单币种汇率',
  `exchange_rate_to_fin` decimal(18,8) DEFAULT NULL COMMENT '账单币种转财务本位币汇率',
  `rate_source_to_bill` varchar(32) DEFAULT NULL COMMENT '账单汇率来源',
  `rate_source_to_fin` varchar(32) DEFAULT NULL COMMENT '财务汇率来源',
  `rate_level_to_bill` varchar(32) DEFAULT NULL COMMENT '账单汇率层级',
  `rate_level_to_fin` varchar(32) DEFAULT NULL COMMENT '财务汇率层级',
  `original_relation_id` bigint DEFAULT NULL COMMENT '原关系ID',
  `replaced_by_relation_id` bigint DEFAULT NULL COMMENT '替换后的关系ID',
  `adjustment_no` varchar(64) DEFAULT NULL COMMENT '调整单号',
  `source_version_no` bigint NOT NULL DEFAULT '1' COMMENT '来源版本号',
  `sc_id` bigint NOT NULL COMMENT '供应链ID',
  `shop_id` bigint NOT NULL COMMENT '店铺ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `created_by` varchar(64) DEFAULT NULL COMMENT '创建人',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `updated_by` varchar(64) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_bill_fee_relation_no` (`relation_no`),
  KEY `idx_bill_relation_status` (`bill_no`, `bill_type`, `relation_status`),
  KEY `idx_fee_detail_relation_status` (`fee_detail_id`, `relation_status`),
  KEY `idx_bill_fee_detail_type` (`bill_id`, `fee_detail_id`, `relation_type`)
) COMMENT='账单费用关系表';
